#!/bin/bash
#assign weights to PIV data based on the std.dev. of the 
#images used to calculate the PIV data

export PATH=$PATH:/usr/local/bin:/mnt/data/prog/tiff:/mnt/data/prog/tools

if [ "$#" == "0" ]; then
	echo "$0 piv.data imgA imgB norm.file > piv-w.data"
	exit
fi


piv=$1
imgA=$2
imgB=$3
norm=$(cat $4)

#	lattice distance of PIV data (pixels)
piv_d=16


#	internal variables
tmp=$(tempfile); rm ${tmp}
ph=$(echo ${piv_d} | awk '{print $1 /2}')


imgstddev -w ${ph} -f ${imgA} -m |\
	pnmsmooth -size 5 5 > ${tmp}.a.pgm
imgstddev -w ${ph} -f ${imgB} -m |\
	pnmsmooth -size 5 5 > ${tmp}.b.pgm


grep -v NaN $piv | pixlist.py ${tmp}.a.pgm |\
   	awk "{print \$1, \$2, \$3, \$4, \$5/$norm}"  > ${tmp}.piva
grep -v NaN $piv | awk '{print $1+$3, $2+$4}' | \
	pixlist.py ${tmp}.b.pgm |\
   	awk "{print \$5/$norm}" | paste ${tmp}.piva -  | \
	awk '{if ($5>$6) print $1,$2,$3,$4,$5; else print $1,$2,$3,$4,$6}'

rm -rf ${tmp}.piva ${tmp}.a.pgm ${tmp}.b.pgm 

